project:
  type: book
  output-dir: docs

book:
  title: "Security, Privacy, and Ethics"
  author: "Claire McKay Bowen, PhD"
  date: today
  chapters:
    - index.qmd
    - part: Week 1 - Introduction
      chapters:
        - 00_basics.qmd
        - 01_security-privacy-ethics.qmd
        
    - part: Week 2 - Data Collection and Acquisition
      chapters: 
        - 02_data-collection.qmd

    - part: Week 3 - Data Storage and Sharing
      chapters: 
        - 03_data-storage.qmd
        - 03_data-sharing-transfer.qmd

    - part: Week 4 - Data Analysis and Presentation Prep
      chapters: 
        - 04_data-analysis.qmd
        - 04_better-presentations.qmd

    - part: Week 5 - Data Dissemination
      chapters: 
        - 05_data-dissemination-part1.qmd
        - 05_data-dissemination-part2.qmd
        
    - part: Week 6 - Data Destruction, Termination, and the Future
      chapters: 
        - 06_data-termination.qmd
        
    - part: Week 7 - Final Presentations
      chapters: 
        - 07_final-presentations.qmd
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 3
    css: www/styles.css