project:
  type: book
  output-dir: docs

book:
  title: "Security, Privacy, and Ethics (+ Equity)"
  author: "Claire McKay Bowen, PhD"
  date: today
  chapters:
    - index.qmd
    - part: Prelude
      chapters:
        - 01_introduction.qmd
      
    - part: Introduction and Data Collection
      chapters: 
        - 02_security-privacy-ethics-equity.qmd
        - 02_data-collection.qmd

    - part: Data Storage and Sharing
      chapters: 
        - 03_data-storage.qmd
        - 03_data-sharing-transfer.qmd

    - part: Data Analysis
      chapters: 
        - 04_data-analysis-part1.qmd
        - 04_data-analysis-part2.qmd

    - part: Data Dissemination
      chapters: 
        - 05_data-dissemination-part1.qmd
        - 05_data-dissemination-part2.qmd

    - part: Data Destruction and Termination
      chapters: 
        - 06_final-presentations.qmd
        - 06_data-termination.qmd
        
    - part: Non-Technical Professional Skills
      chapters: 
        - 02_written-verbal-communication.qmd
        - 03_job-market-time-management.qmd
        - 04_better-presentations.qmd
        - 05_communication-collaboration-culture.qmd
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 3
    css: www/styles.css